config/routes.rb
Rails.application.routes.draw do
  root :to => "welcome#index"

  get 'artist/dashboard', to: 'artist#dashboard', as: 'artist_dashboard'
  get 'artist/new', to: 'artist#new', as: 'artist_new'
  post 'artist/new', to: 'artist#create'
  get 'artist/:id/delete', to: 'artist#delete', as: 'artist_delete'
  get 'artist/:id/edit', to: 'artist#edit', as: 'artist_edit'
  patch 'artist/:id/update', to: 'artist#update', as: 'artist_update'

  get 'lp/dashboard', to: 'lp#dashboard_filter', as: 'lp_dashboard_filter'
  post 'lp/dashboard', to: 'lp#dashboard_filter_result', as: 'lp_dashboard_filter_result'
  get 'artist/:id_artist/lp', to: 'lp#dashboard', as: 'lp_dashboard'
  get 'artist/:id_artist/lp/new', to: 'lp#new', as: 'lp_new'
  post 'artist/:id_artist/lp/new', to: 'lp#create'
  get 'artist/:id_artist/lp/:id/delete', to: 'lp#delete', as: 'lp_delete'
  get 'artist/:id_artist/lp/:id/edit', to: 'lp#edit', as: 'lp_edit'
  patch 'artist/:id_artist/lp/:id/update', to: 'lp#update', as: 'lp_update'
end

app/models/artist.rb
class Artist < ActiveRecord::Base
	has_one :lp
end

app/models/lp.rb
class Lp < ActiveRecord::Base
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artist_controller.rb
class ArtistController < ApplicationController

	def dashboard
		@artists = Artist.all
	end

	def new
		@artist = Artist.new
	end

	def create 
	    @artist = Artist.new(artist_params)
	    if @artist.save
	    	redirect_to artist_dashboard_path
	    else
	    	render :new
	    end
	end

	def edit 
		@artist = Artist.find(params[:id])
	end

	def update
		@artist = Artist.find(params[:id])

    	Artist.transaction do
	    	if @artist.update_attributes(artist_params)
	        	redirect_to artist_dashboard_path
	    	else
	    		render :edit
	      	end
	    end
    end

	def delete 
		artist = Artist.find(params[:id])
		artist.destroy
		redirect_to artist_dashboard_path
	end

	private

	def artist_params
    	params.require(:artist).permit(:name,
                                   :description)
  	end
end

app/controllers/lp_controller.rb
class LpController < ApplicationController

	def dashboard
		@lps = Lp.where(artist_id: params[:id_artist])
		@artist_id = params[:id_artist]
	end

	def dashboard_filter
		@lps = Lp.all
	end

	def dashboard_filter_result
		@artist_id = params[:artist][:artist]
		@lps = Lp.where(artist_id: @artist_id)
		render 'dashboard_filter'
	end

	def new
		@lp = Lp.new
		@artist_id = params[:id_artist]
	end

	def create
		@lp = Lp.new(lp_params)
		@lp.artist_id = params[:id_artist]
	    if @lp.save
	    	redirect_to lp_dashboard_path
	    else
	    	render :new
	    end
	end

	def edit
		@lp = Lp.find(params[:id])
		@artist_id = params[:id_artist]
	end

	def update
		@lp = Lp.find(params[:id])
		puts params[:id_artist]
		@lp.artist_id = params[:id_artist]

    	Lp.transaction do
	    	if @lp.update_attributes(lp_params)
	        	redirect_to lp_dashboard_path
	    	else
	    		render :edit
	      	end
	    end
	end

	def delete
		lp = Lp.find(params[:id])
		lp.destroy
		redirect_to lp_dashboard_path
	end

	private

	def lp_params
    	params.require(:lp).permit(:name,
                                   :description)
  	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artist_helper.rb
module ArtistHelper
end

app/helpers/lp_helper.rb
module LpHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/artist/_form.html.erb
<div class="form-group">
	<label>Name Artist</label>
	<%= f.text_field :name, value: @artist.name, placeholder: 'Name', class: 'form-control', required: true %>
</div>

<div class="form-group">
	<label>Description</label>
	<%= f.text_field :description, value: @artist.description, placeholder: 'Description', class: 'form-control', required: true %>
</div>

<%= f.submit 'Create', class: 'btn btn-primary' %>

app/views/artist/dashboard.html.erb
<div class="container">
	<a onclick="location.href='<%= artist_new_path %>'"><button type="button" class="btn btn-primary">New Artist</button></a>	

	<hr>

	<% unless @artists.blank? %>
		<% @artists.each do |artist| %>
			<div class="panel panel-default">
				<div class="panel-body">
			    	<h3><%= artist.name %></h3>
			    	<p><%= artist.description %></p>
			    	<span class="btn-group pull-right">
			    		<a class="btn btn-success btn-sm" onclick="location.href='<%= lp_dashboard_path(artist.id) %>'">LP</a>
				        <a class="btn btn-info btn-sm" onclick="location.href='<%= artist_edit_path(artist.id) %>'">Edit</a>
				        <a class="btn btn-danger btn-sm" onclick="location.href='<%= artist_delete_path(artist.id) %>'">Delete</a>
				    </span>
			  	</div>
			</div>
		<% end %>
	<% end %>
</div>

app/views/artist/edit.html.erb
<div class="container">
	<%= form_for @artist, url: artist_update_path(@artist) do |f| %>
		<%= render 'artist/form', f: f %>
	<% end %>
</div>

app/views/artist/new.html.erb
<div class="container">
	<%= form_for @artist, url: artist_new_path(@artist) do |f| %>
		<%= render 'artist/form', f: f %>
	<% end %>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Discography</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to 'Artist', artist_dashboard_path %>
        </li>
        <li>
          <%= link_to 'LP', lp_dashboard_filter_path %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Discography</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	
  	<%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/nav' %>
	<%= yield %>

</body>
</html>

app/views/lp/_form.html.erb
<div class="form-group">
	<label>Name LP</label>
	<%= f.text_field :name, value: @lp.name, placeholder: 'Name', class: 'form-control', required: true %>
</div>

<div class="form-group">
	<label>Description</label>
	<%= f.text_field :description, value: @lp.description, placeholder: 'Description', class: 'form-control', required: true %>
</div>

<%= f.submit 'Create', class: 'btn btn-primary' %>

app/views/lp/dashboard.html.erb
<div class="container">
	<a onclick="location.href='<%= lp_new_path(@artist_id) %>'"><button type="button" class="btn btn-primary">New LP</button></a>	

	<hr>

	<% unless @lps.blank? %>
		<% @lps.each do |lp| %>
			<div class="panel panel-default">
				<div class="panel-body">
			    	<h3><%= lp.name %></h3>
			    	<p><%= lp.description %></p>
			    	<span class="btn-group pull-right">
						<a class="btn btn-info btn-sm" onclick="location.href='<%= lp_edit_path(@artist_id, lp.id) %>'">Edit</a>
				        <a class="btn btn-danger btn-sm" onclick="location.href='<%= lp_delete_path(@artist_id, lp.id) %>'">Delete</a>
				    </span>
			  	</div>
			</div>
		<% end %>
	<% end %>
</div>

app/views/lp/dashboard_filter.html.erb
<div class="container">

	<div class="col-sm-4">
      <%= form_for :artist, url: lp_dashboard_filter_result_path do |f|
        f.select :artist, options_for_select(Artist.all.map {|t| [t.name, t.id]}, @carrier_id), {include_blank: 'Select'}, {:onchange => "this.form.submit();", class: 'input-field float-right'}
      end %>
    </div>

	<hr>

	<% unless @lps.blank? %>
		<% @lps.each do |lp| %>
			<div class="panel panel-default">
				<div class="panel-body">
			    	<h3><%= lp.name %></h3>
			    	<p><%= lp.description %></p>
			  	</div>
			</div>
		<% end %>
	<% end %>


</div>

app/views/lp/edit.html.erb
<div class="container">
	<%= form_for @lp, url: lp_update_path(@artist_id, @lp.id, @lp) do |f| %>
		<%= render 'lp/form', f: f %>
	<% end %>
</div>

app/views/lp/new.html.erb
<div class="container">
	<%= form_for @lp, url: lp_new_path(@artist_id, @lp) do |f| %>
		<%= render 'lp/form', f: f %>
	<% end %>
</div>

app/views/welcome/index.html.erb
<h1 class="text-center">Welcome to the Application Discography</h1>